# .github/workflows/scheduled-tasks.yml
name: Scheduled Tasks

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-or-maintain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Run maintenance script
        run: |
          if [ -f ./run.js ]; then
            node run.js
          else
            echo "no run.js; running placeholder maintenance"
            date > last-run.txt
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: scheduled-output
          path: |
            last-run.txt
            public
            out
            .
